#!/usr/bin/env python3

import sys
from pathlib import Path

try:
    from PIL import Image, ImageOps
except ImportError as exc:
    raise SystemExit("Pillow is required to convert LCD PNG backgrounds: python3 -m pip install Pillow") from exc


LCD_WIDTH = 320
LCD_HEIGHT = 170


def srgb_to_linear(value):
    value = value / 255.0
    if value <= 0.04045:
        return value / 12.92
    return ((value + 0.055) / 1.055) ** 2.4


def quantize_channel(value, bits):
    levels = (1 << bits) - 1
    quantized = int(round(srgb_to_linear(value) * levels))
    return min(levels, max(0, quantized))


def pack_rgb565(r5, g6, b5):
    return (r5 << 11) | (g6 << 5) | b5


def rgb565_pixels(image):
    pixels = []
    data = image.get_flattened_data() if hasattr(image, "get_flattened_data") else image.getdata()
    for pixel in data:
        r, g, b = pixel[:3]
        pixels.append(pack_rgb565(quantize_channel(r, 5), quantize_channel(g, 6), quantize_channel(b, 5)))
    return pixels


def load_background(path, fallback):
    if not path.exists():
        return [fallback] * (LCD_WIDTH * LCD_HEIGHT)

    image = Image.open(path).convert("RGB")
    if image.size == (LCD_HEIGHT, LCD_WIDTH):
        image = image.rotate(-90, expand=True)
    if image.size != (LCD_WIDTH, LCD_HEIGHT):
        image = ImageOps.fit(image, (LCD_WIDTH, LCD_HEIGHT), method=Image.Resampling.LANCZOS)
    return rgb565_pixels(image)


def write_array(out, name, pixels):
    out.write(f"static const uint16_t {name}[LCD_BACKGROUND_WIDTH * LCD_BACKGROUND_HEIGHT] = {{\n")
    for index in range(0, len(pixels), 12):
        chunk = pixels[index:index + 12]
        values = ", ".join(f"0x{pixel:04x}" for pixel in chunk)
        out.write(f"  {values},\n")
    out.write("};\n\n")


def main():
    if len(sys.argv) != 4:
        print("usage: convert_lcd_backgrounds.py OUT_HEADER LIGHT_PNG DARK_PNG", file=sys.stderr)
        return 2

    output = Path(sys.argv[1])
    light_png = Path(sys.argv[2])
    dark_png = Path(sys.argv[3])
    output.parent.mkdir(parents=True, exist_ok=True)

    light = load_background(light_png, 0xFFFF)
    dark = load_background(dark_png, 0x0000)

    with output.open("w", encoding="utf-8") as out:
        out.write("#pragma once\n\n")
        out.write("#include <stdint.h>\n\n")
        out.write("/* Generated by scripts/tools/convert_lcd_backgrounds.py. Do not edit directly.\n")
        out.write("   Backgrounds are uncompressed RGB565 pixels in scanline order so the LCD\n")
        out.write("   renderer can memcpy them into the DMA-capable transfer buffer. */\n\n")
        out.write(f"#define LCD_BACKGROUND_WIDTH {LCD_WIDTH}\n")
        out.write(f"#define LCD_BACKGROUND_HEIGHT {LCD_HEIGHT}\n\n")
        write_array(out, "g_lcd_background_light", light)
        write_array(out, "g_lcd_background_dark", dark)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
